- name: Simulação de Integração com ServiceNow
  hosts: all
  connection: local
  vars:
    servicenow_instance: 'https://sua_instancia.service-now.com'  # URL da sua instância
    servicenow_user: 'seu_usuario'
    servicenow_password: 'sua_senha'
  tasks:
    - name: Criar um novo incidente
      community.general.servicenow_incident:
        state: present
        instance: "{{ servicenow_instance }}"
        username: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        short_description: "Incidente de teste criado pelo Ansible"
        description: "Este é um incidente de teste para simular a integração com o ServiceNow."
      register: new_incident
    - name: Exibir informações do incidente criado
      debug:
        msg: "Incidente criado com o número {{ new_incident.incident.number }}"
    - name: Atualizar o incidente com uma nova descrição
      community.general.servicenow_incident:
        state: present
        instance: "{{ servicenow_instance }}"
        username: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        number: "{{ new_incident.incident.number }}"
        description: "Descrição do incidente atualizada pelo Ansible"
    - name: Consultar o incidente atualizado
      community.general.servicenow_incident:
        state: present
        instance: "{{ servicenow_instance }}"
        username: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        number: "{{ new_incident.incident.number }}"
        display_value: true
      register: updated_incident
    - name: Exibir informações do incidente atualizado
      debug:
        msg: "{{ updated_incident.incident }}"
