- name: Simulação de Integração com ServiceNow
  hosts: localhost
  connection: local
  vars:
     servicenow_instance: 'https://sua_instancia.service-now.com'
     servicenow_user: 'seu_usuario'
     servicenow_password: 'sua_senha'

  tasks:
    - name: Criar um novo incidente
      community.general.servicenow_incident:
        state: present
        instance: "{{ servicenow_instance }}"
        username: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        short_description: "Incidente de teste criado pelo Ansible"
        description: "Este é um incidente de teste para simular a integração com o ServiceNow."
      register: new_incident

    - name: Exibir número do incidente criado
      debug:
        var: new_incident.incident.number

    - name: Aguardar 5 segundos para o incidente ser processado
      wait_for:
        timeout: 5

    - name: Consultar o incidente criado
      community.general.servicenow_incident:
        state: present
        instance: "{{ servicenow_instance }}"
        username: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        number: "{{ new_incident.incident.number }}"
      register: retrieved_incident

    - name: Exibir informações do incidente criado
      debug:
        var: retrieved_incident.incident

    - name: Atualizar o incidente com uma nova descrição
      community.general.servicenow_incident:
        state: present
        instance: "{{ servicenow_instance }}"
        username: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        number: "{{ new_incident.incident.number }}"
        description: "Descrição do incidente atualizada pelo Ansible"

    - name: Aguardar 5 segundos para o incidente ser processado
      wait_for:
        timeout: 5

    - name: Consultar o incidente atualizado
      community.general.servicenow_incident:
        state: present
        instance: "{{ servicenow_instance }}"
        username: "{{ servicenow_user }}"
        password: "{{ servicenow_password }}"
        number: "{{ new_incident.incident.number }}"
      register: updated_incident

    - name: Exibir informações do incidente atualizado
      debug:
        var: updated_incident.incident
